# ======================================================================================
#                                 WELCOME TO THE CONFIG
#                                          FOR
#                                     MODERN LEVELS
# ======================================================================================
# NOTE: BOT_TOKEN & MONGO CLIENT DETAILS ARE STORED IN THE .env FILE!
# The prefix for the bots commands
Prefix: "!"

# Set what the bot is currently playing
bot_status_text: "[!] | Modern Levels"

# IDLE, DND, ONLINE, OFFLINE
bot_activity: online


# ======================================================================================
#                                      CHANNELS
# ======================================================================================
# The channel where level up messages will be sent to
level_message_channel: 

# Sends a message to a specific channel if a new user joins, or an existing user leaves
join_leave_message: False

# The channel where join / leave messages will be sent to (If enabled)
join_leave_channel: 


# ======================================================================================
#                                      ROLES
# ======================================================================================
# The role a user will get on joining the server (NOT CHANNEL ID!! + If join_leave_message is True)
on_join_role: 'Member'

# Enables / Disables adding role when a user joins the guild
add_role: True

# Admin Role for admin type commands - CASE SENSITIVE
admin_role: "🕹️| Admin"

# Array of roles you can be rewarded for levelling up. Rank for each role, in same order as level_roles. *Case sensitive*
level_roles: ["role1", "role2", "role3"]
level_roles_num: [1, 2, 3]


# ======================================================================================
#                                      XP
# ======================================================================================
# How much XP you earn per message
xp_per_message: 10

# How much XP is required per level (e.g - xp_per_level: 10 = Level 1 would require 10 xp to level up. Level 2 would require 20 xp to level up)
xp_per_level: 100

# Double XP Role:
double_xp: "Double XP"

# Sends a level up message if a user has reached the set amount of xp
show_levelup_message: True

# sends a message if a user has unlocked a new role from levelling up
show_newrole_message: True


# ======================================================================================
#                                      LEADERBOARD
# ======================================================================================
# Amount of users to be shown on the leaderboard
leaderboard_amount: 10

# Sets the image that displays on the leaderboard embed
leaderboard_image: "https://cdn.discordapp.com/attachments/812895798496591882/825363205853151252/ML_1.png"

# Sets aliases for the leaderboard command
leaderboard_alias: ['lb', 'leader', 'rankings']


# ======================================================================================
#                                      RANK
# ======================================================================================
# Sets aliases for the rank command
rank_alias: ['r', 'level', 'l', 'stats', 'xp', 'progress']


# ======================================================================================
#                                      EMBED
# ======================================================================================
# Rank Embed Colour | Must Be Hex Notation
rank_embed_colour: 0x4863A0

# Leaderboard Embed Colour | Must Be Hex Notation (Replace # with 0x)
leaderboard_embed_colour: 0x4863A0

# Embed Colour | Must Be Hex Notation
embed_colour: 0x4863A0

# Error Embed Colour | Must Be Hex Notation
error_embed_colour: 0x4863A0

# Success Embed Colour | Must Be Hex Notation
success_embed_colour: 0x4863A0


# ======================================================================================
#                                      HELP
# ======================================================================================
# True/False - <prefix>help command
help_command: True


# ======================================================================================
#                                      THE END
# ======================================================================================



